# LLM Guardrails (FIXED)
# Updated: [
  "weather",
  "news",
  "movie recommendation",
  "tv show",
  "music recommendation",
  "book recommendation",
  "celebrity",
  "gossip",
  "sports score",
  "game score",
  "restaurant",
  "food recommendation",
  "recipe",
  "cooking",
  "diet",
  "fitness",
  "workout",
  "health advice",
  "medical advice",
  "therapy",
  "dating",
  "relationship advice",
  "fashion advice",
  "styling",
  "legal advice",
  "lawyer",
  "lawsuit",
  "cryptocurrency",
  "crypto",
  "stock tips",
  "investment advice",
  "tax advice",
  "insurance",
  "politics",
  "political opinion",
  "religion",
  "religious",
  "spiritual",
  "travel destination",
  "hotel recommendation",
  "flight booking",
  "real estate",
  "property",
  "car buying",
  "vehicle",
  "gaming",
  "video game",
  "homework",
  "essay writing",
  "translation",
  "language learning"
]
